remote_theme: pmarsceill/just-the-docs
repository_url: ""
title: Главная
markdown: GFM
footer_content: "© 2025 Все права защищены."
show_related: false
search_enabled: true

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: "" 
    values:
      layout: default
