remote_theme: pmarsceill/just-the-docs
title: Главная
repository_url: ""
markdown: GFM

# Включаем автоматическую генерацию навигации
defaults:
  - scope:
      path: "" 
    values:
      layout: default

# Включаем Jekyll collections, чтобы поддерживать папки
collections:
  about:
    output: true
  Маркетинг:
    output: true
