remote_theme: pmarsceill/just-the-docs
repository_url: ""
title: Главная
markdown: GFM
footer_content: "© 2025 Все права защищены."
# Убираем ссылку на сайт слева под меню https://github.com/just-the-docs/just-the-docs
show_related: false

# Включаем автоматическую генерацию навигации
defaults:
  - scope:
      path: "" 
    values:
      layout: default

# Включаем Jekyll collections, чтобы поддерживать папки
collections:
  about:
    output: true
  Маркетинг:
    output: true
